### ISSUE TITLE
DollarNames.R error (in the latest version of RStudio)

### ISSUE THREAD

**Issue by rguliev** [cbeleites/hyperSpec#34] opened 2017-02-10 14:31 UTC
Hi,
Recently, I updated my R Studio to the latest version of R Stutio (1.0.136). And now the following error keeps popping up, when I try to use 'spc$' instead "spc@data$":
`Error in grep(pattern, colnames(x@data), value = TRUE) : 
  argument "pattern" is missing, with no default`
The message pops up each time a character is typed. I.e. after typing `flu$file` console looks like this:
```
Error in grep(pattern, colnames(x@data), value = TRUE) : 
  argument "pattern" is missing, with no default
Error in grep(pattern, colnames(x@data), value = TRUE) : 
  argument "pattern" is missing, with no default
Error in grep(pattern, colnames(x@data), value = TRUE) : 
  argument "pattern" is missing, with no default
Error in grep(pattern, colnames(x@data), value = TRUE) : 
  argument "pattern" is missing, with no default
Error in grep(pattern, colnames(x@data), value = TRUE) : 
  argument "pattern" is missing, with no default
> flu$file
```
I've checked this on 3 different computers and this orrurs on all of them. 

P.S. I also tried to fix it on my own. But the message doesn't occur (neither '$' works)  when I load 'hyperSpec' from local ( `devtools::load_all(".")`). Perhaps, I still doing something wrong with package building..

**Comment by cbeleites** [comment] 2017-02-10 18:10
I confirm this in the newest RStudio version. 
Console R works for me. 

I think the problem is that `hyperSpec`'s  `.DollarNames`-method doesn't have the default pattern `""`

**Comment by rguliev** [comment] 2017-02-11 09:03
Yes, I think that too. And I found a way to check it:
```
f <- function (x, pattern) {grep (pattern, colnames (x@data), value = TRUE)}
> f(flu)
Error in grep(pattern, colnames(x@data), value = TRUE) : 
  argument "pattern" is missing, with no default
> f(flu,"")
[1] "file" "spc"  "c"
```
So, all we need is to change `.DollarNames.hyperSpec <- function (x, pattern)` to `.DollarNames.hyperSpec <- function (x, pattern="")`

P.S. I think it's not that big change for me making a pull request:) I hope you think so too.

**Comment by cbeleites** [comment] 2017-02-11 10:18
:-) yes I think so, too.
In fact, I pushed the change in branch `issue-DollarNames-34` yesterday evening ;-) 
just didn't have the time to completely run the tests and then merge it into master.

**Comment by ximeg** [comment] 2017-02-20 09:20
Hey, I just wanted to file a bug report on this issue here, and you already solved the problem! Great! :+1:

**Comment by cbeleites** [comment] 2017-03-07 16:44
fixed by https://github.com/cbeleites/hyperSpec/commit/3fec03bc98f3b1bbc77e81ef8618da7d6e48ab08

**Closed by cbeleites** 2017-03-07 16:44 UTC
Labels: bug
